engines:
  eslint:
    enabled: true
    config:
      config: path/to/.eslintrc
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.js"
exclude_paths:
- node_modules
- "**/vendor/**/*"
