engines:
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.js"
exclude_paths:
- node_modules
- "**/vendor/**/*"
